import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from '@/app/providers';
import React from 'react';
import HeaderNav from '@/components/HeaderNav';
import { Box, Flex, Text } from '@chakra-ui/react';

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`} suppressHydrationWarning>
        <body>
        <Providers>
            <Flex direction="column" minHeight="100vh" alignItems="center" mx="auto">
                <HeaderNav />
                <Box maxW="4xl" w="full" px={6} py={4} flexGrow={1} bg="bg">
                    {children}
                </Box>
                <footer style={{width: '100%'}}>
                    <Box bg="subtleBg" w="full" textAlign="center" py={2}>
                        <Text fontSize="sm">footer</Text>
                    </Box>
                </footer>
            </Flex>
        </Providers>
        </body>
        </html>
    )
}
