import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from '@/app/providers';
import React from 'react';
import HeaderNav from '@/components/HeaderNav';
import { Flex } from '@chakra-ui/react';
import Footer from '@/components/Footer';

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`} suppressHydrationWarning>
        <body>
        <Providers>
            <Flex direction="column" minHeight="100vh" alignItems="center" mx="auto">
                <HeaderNav />
                    {children}
                <Footer/>
            </Flex>
        </Providers>
        </body>
        </html>
    )
}
